name: "changesets Release"

on:
  pull_request_target:
    branches:
      - dev
      - master
    paths:
      - "**/CHANGELOG.md"
    types:
      - closed

jobs:
  unit-tests:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/')
    uses: ./.github/workflows/reusable-unit-tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  api-library-tests:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/')
    uses: ./.github/workflows/reusable-api-library-tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # nextjs-app-setup:
  #   uses: ./.github/workflows/reusable-nextjs-app-setup.yml

  package-tests:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/')
    uses: ./.github/workflows/reusable-package-tests.yml

  integration-tests-on-prem:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/')
    uses: ./.github/workflows/reusable-integration-tests-on-prem.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  toolbox-tests:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/')
    uses: ./.github/workflows/reusable-toolbox-tests.yml

  aura-free-tests:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/')
    uses: ./.github/workflows/reusable-aura-tests.yml
    with:
      CONTINUE_ON_ERROR: true
    secrets:
      URI: ${{ secrets.AURA_FREE_URI }}
      PASSWORD: ${{ secrets.AURA_FREE_PASSWORD }}
    concurrency: aura-free

  aura-professional-tests:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/')
    uses: ./.github/workflows/reusable-aura-tests.yml
    with:
      CONTINUE_ON_ERROR: true
    secrets:
      URI: ${{ secrets.AURA_PROFESSIONAL_URI }}
      PASSWORD: ${{ secrets.AURA_PROFESSIONAL_PASSWORD }}
    concurrency: aura-professional

  # slack-release-notification:
  #   needs:
  #     - bump-version

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Send Slack notification of upcoming release
  #       id: slack-notification
  #       uses: slackapi/slack-github-action@v1.19.0
  #       with:
  #         payload: '{"version":"${{ needs.bump-version.outputs.version }}"}'
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_NOTIFICATION_WEBHOOK_URL }}

  publish:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/')

    needs:
      - unit-tests
      - api-library-tests
      - package-tests
      - integration-tests-on-prem
      - toolbox-tests
      - aura-free-tests
      - aura-professional-tests

    runs-on: ubuntu-latest

    environment:
      name: npm

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @neo4j:registry https://registry.npmjs.org
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: changeset publish
        run: yarn changeset publish
      - name: git push
        run: git push --follow-tags

  # Merge into master for a standard release
  merge-into-master:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/') &&
      github.base_ref == 'dev'

    needs:
      - publish

    runs-on: ubuntu-latest

    environment:
      name: github

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
      - name: git config
        run: |
          git config --global user.name 'Neo4j Team GraphQL'
          git config --global user.email 'team-graphql@neotechnology.com'
      - name: git merge
        run: git merge --no-ff origin/dev --strategy-option theirs
      - name: git push
        run: git push

  # Create a PR into dev for a hotfix release
  pr-into-dev:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'neo4j-team-graphql' &&
      startsWith(github.head_ref, 'changeset-release/') &&
      github.base_ref == 'master'

    needs:
      - publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: repo-sync/pull-request@65785d95a5a466e46a9d0708933a3bd51bbf9dde # renovate: tag=v2.6.2
        with:
          destination_branch: "dev"
          pr_title: "Merge ${{ github.ref }} into dev"
          github_token: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}

  # slack-release-announcement:
  #   needs:
  #     - bump-version
  #     - changelog

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Send Slack announcement of release
  #       id: slack-announcement
  #       uses: slackapi/slack-github-action@v1.19.0
  #       with:
  #         payload: '{"version":"${{ needs.bump-version.outputs.version }}"}'
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_ANNOUNCEMENT_WEBHOOK_URL }}
