name: "dev"

on:
  push:
    branches:
      - dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  # Let's consider the value of testing examples
  # Perhaps we need some newer, better examples for testing
  neo-push-tests:
    uses: ./.github/workflows/reusable-neo-push-tests.yml

  unit-tests:
    uses: ./.github/workflows/reusable-unit-tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  api-library-tests:
    uses: ./.github/workflows/reusable-api-library-tests.yml

  # nextjs-app-setup:
  #   uses: ./.github/workflows/reusable-nextjs-app-setup.yml

  package-tests:
    uses: ./.github/workflows/reusable-package-tests.yml

  integration-tests-on-prem:
    uses: ./.github/workflows/reusable-integration-tests-on-prem.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  toolbox-tests:
    uses: ./.github/workflows/reusable-toolbox-tests.yml

  aura-tests:
    uses: ./.github/workflows/reusable-aura-tests.yml
    secrets: inherit
    concurrency: aura
