name: "Documentation Pub"

on:
  pull_request:
    branches:
      - fix/gha-doc-publish

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Build documentation
        run: |
          yarn
          yarn build
        working-directory: docs/
      - name: Publish documentation
        run: |
          npm install -g surge
          surge ./site neo4j-graphql-docs-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        working-directory: docs/
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          message: |
            Looks like you've updated the documentation!

            Check out your changes at https://neo4j-graphql-docs-${{ github.event.pull_request.number }}.surge.sh
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
