name: "Pull Request Labeler"

on:
  pull_request_target:
    branches:
      - dev
      - master

jobs:
  label:
    if: "!startsWith(github.event.pull_request.head.ref, 'renovate/')"

    runs-on: ubuntu-latest

    steps:
      - uses: srvaroa/labeler@f81537c46929f589191a22349a885eb076024860 # v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.NEO4J_TEAM_GRAPHQL_PERSONAL_ACCESS_TOKEN }}
