name: "Pull Request"

on:
  pull_request:
    branches:
      - dev
      - master
    paths-ignore:
      - "docs/**"

jobs:
  reviewdog-eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - uses: reviewdog/action-eslint@d3395027ea2cfc5cf8f460b1ea939b6c86fea656
        with:
          fail_on_error: true
          eslint_flags: "."

  package-tests:
    uses: ./.github/workflows/reusable-package-tests.yml

  neo-push-tests:
    uses: ./.github/workflows/reusable-neo-push-tests.yml

  typescript-changes:
    runs-on: ubuntu-latest

    outputs:
      typescript: ${{ steps.filter.outputs.typescript }}
      typescript_files: ${{ steps.filter.outputs.typescript_files }}

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@8c7f485a57f7cad3483dcc0fdf36122a0542f200
        id: filter
        with:
          list-files: shell
          filters: |
            typescript:
              - added|modified: 'packages/**/*.ts'

  license-header-check:
    needs: typescript-changes
    if: ${{ needs.typescript-changes.outputs.typescript == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.17.0"
      - name: Install addlicense
        run: go install github.com/google/addlicense@latest
      - name: Run addlicense
        run: addlicense -f ./addlicense -check ${{ needs.typescript-changes.outputs.typescript_files }}

  unit-tests:
    uses: ./.github/workflows/reusable-unit-tests.yml

  e2e-tests-plugins:
    uses: ./.github/workflows/reusable-subscriptions-plugin-amqp-e2e-test.yml

  api-library-tests:
    uses: ./.github/workflows/reusable-api-library-tests.yml

  # nextjs-app-setup:
  #   uses: ./.github/workflows/reusable-nextjs-app-setup.yml

  toolbox-tests:
    uses: ./.github/workflows/reusable-toolbox-tests.yml

  integration-tests-on-prem:
    uses: ./.github/workflows/reusable-integration-tests-on-prem.yml
