name: "Perform actions in Trello following release"

on:
  release:
    types:
      - published

jobs:
  create-trello-list:
    runs-on: ubuntu-latest

    environment: trello

    steps:
      - name: Create list
        run: |
          list=$( curl --request POST --url "https://api.trello.com/1/lists?name=${{ github.event.release.name }}&idBoard=${{ secrets.TEAM_GRAPHQL_BOARD }}&key=${{ secrets.API_KEY }}&token=${{ secrets.API_TOKEN }}&pos=bottom" | jq .id )
          echo "LIST=$list" >> "$GITHUB_ENV"
      - name: Create changelog card
        run: |
          card=$( curl --request POST --url "https://api.trello.com/1/cards?idList=$LIST&name=${{ github.event.release.name }}&desc=${{ github.event.release.body }}&key=${{ secrets.API_KEY }}&token=${{ secrets.API_TOKEN }}" --header 'Accept: application/json' | jq .id )
          echo "CARD=$card" >> "$GITHUB_ENV"
      - name: Attach release
        run: |
          curl --request POST --url "https://api.trello.com/1/cards/${CARD}/attachments?url=${{ github.event.release.html_url }}&key=${{ secrets.API_KEY }}&token=${{ secrets.API_TOKEN }}" --header 'Accept: application/json'
