name: "Aura tests"

on:
  workflow_call:
    secrets:
      AURA_FREE_URI:
        required: true
        description: "URI locating the AuraDB Free instance to test against"
      AURA_FREE_PASSWORD:
        required: true
        description: "Password of the AuraDB Free instance to test against"
      AURA_PROFESSIONAL_URI:
        required: true
        description: "URI locating the AuraDB Professional instance to test against"
      AURA_PROFESSIONAL_PASSWORD:
        required: true
        description: "Password of the AuraDB Professional instance to test against"

jobs:
  aura-teardown:
    strategy:
      matrix:
        aura-instance:
          - free
          - professional

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Install ts-node and typescript
        run: npm install -g ts-node typescript
      - name: Uppercase instance name
        run: |
          lowercase_instance=${{ matrix.aura-instance }}
          echo "AURA_URI_SECRET=AURA_${lowercase_instance^^}_URI" >>"${GITHUB_ENV}"
          echo "AURA_PASSWORD_SECRET=AURA_${lowercase_instance^^}_PASSWORD" >>"${GITHUB_ENV}"
      - name: Delete all data in instance
        run: ts-node tests/integration/teardown.ts
        working-directory: packages/graphql
        env:
          NEO_USER: neo4j
          NEO_PASSWORD: ${{ secrets[env.AURA_PASSWORD_SECRET] }}
          NEO_URL: ${{ secrets[env.AURA_URI_SECRET] }}

  integration-tests-aura:
    needs:
      - aura-teardown

    strategy:
      matrix:
        package:
          - graphql
          - introspector
          - ogm
        aura-instance:
          - free
          - professional

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable
      - name: Uppercase instance name
        run: |
          lowercase_instance=${{ matrix.aura-instance }}
          echo "AURA_URI_SECRET=AURA_${lowercase_instance^^}_URI" >>"${GITHUB_ENV}"
          echo "AURA_PASSWORD_SECRET=AURA_${lowercase_instance^^}_PASSWORD" >>"${GITHUB_ENV}"
      - name: Run @neo4j/graphql integration tests
        run: |
          yarn test:int --coverage
          mv coverage coverage-aura-${{ matrix.aura-instance }}
        working-directory: packages/${{ matrix.package }}
        env:
          NEO_USER: neo4j
          NEO_PASSWORD: ${{ secrets[env.AURA_PASSWORD_SECRET] }}
          NEO_URL: ${{ secrets[env.AURA_URI_SECRET] }}
