name: "Apollo Federation Compatibility Tests"

on:
  workflow_call:

jobs:
  federation-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build compatibility test subgraph
        run: |
          yarn build
          ls -la dist/
        working-directory: packages/apollo-federation-subgraph-compatibility
      - uses: apollographql/federation-subgraph-compatibility@v1
        with:
          # [Required] Docker Compose file to start up the subgraph
          compose: "packages/apollo-federation-subgraph-compatibility/docker-compose-gha.yml"
          # [Required] Path to the GraphQL schema file
          schema: "packages/apollo-federation-subgraph-compatibility/schema.graphql"
          # Boolean flag to indicate whether any failing test should fail the script
          failOnWarning: false
          # Boolean flag to indicate whether any failing required functionality test should fail the script
          failOnRequired: true
          debug: true
