name: "UI Build"

on:
  workflow_dispatch:

  pull_request:
    branches:
      - dev
    paths:
      - "packages/graphql/src/**"
      - "packages/graphql-toolbox/**"

jobs:
  build-ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Create the env file
        uses: SpicyPizza/create-envfile@041383d6577d09916e24632ef274f18ec2909b4f # tag=v1.3.1
        with:
          envkey_SEGMENT_GRAPHQL_TOOLBOX_DEV_SOURCE: ${{ secrets.SEGMENT_GRAPHQL_TOOLBOX_DEV_SOURCE }}
          envkey_SEGMENT_GRAPHQL_TOOLBOX_PROD_SOURCE: ${{ secrets.SEGMENT_GRAPHQL_TOOLBOX_PROD_SOURCE }}
          envkey_TEST: "test"
          file_name: .env
          fail_on_empty: false
          directory: packages/graphql-toolbox
      - name: UI build
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          [ -f ./.env ] && echo "exists" || echo 0
          cat ./.env
          yarn install
          yarn build
          echo "$PULL_REQUEST_NUMBER" > ./dist/prnumber
        working-directory: packages/graphql-toolbox
      - name: Archive UI
        uses: actions/upload-artifact@v3
        with:
          name: graphqlui
          path: packages/graphql-toolbox/dist
